DEBUG:
  user: "heggens"

databases:
  laborstatusforms: "data/laborstatus.sql"

db:
  db_name: mysql
  host: localhost
  password: ''
  username: root

log:
  filename: "changeme"

terms:
  spring:
    "Spring 2019"
  fall:
    "Fall 2019" 

roles:
  - faculty
  - administrators
  - students  
