version: "3.7"
volumes:
  db:
    driver: local

services:
  app:
    build: .
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      USING_CONTAINER: 'true'

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: "0.0.0.0"
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
