version: "3.7"
volumes:
  db:
    driver: local
services:
  app:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: local
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
