version: "3.7"
services:
  app:
    build: .
    ports:
      - "8080:8080"
  db:
      image: mysql:5.7
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: 'lsf-flask'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'lsf_user'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'password'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'password'
      volumes:
        - ./docker/data/db:/var/lib/mysql

