contributors:
  - name: "Bria Williams"
    username: ""
    year: 2017
  - name: "Katelyn Adams"
    username: ""
    year: 2019
  - name: "Evan Johnson"
    username: "johnsone"
    year: 2019
  - name: "Anne Otieno"
    username: "otienoa"
    year: 2020
  - name: "Jamal Aw Yoonis"
    username: ""
    year: 2020
  - name: "Alex Bryant"
    username: "bryantal"
    year: 2020
  - name: "Basant Phuyal"
    username: "phuyalb"
    year: 2020
  - name: "Roberto Santos Hernandez"
    username: ""
    year: 2021
  - name: "Guillermo Cruz"
    username: ""
    year: 2021
  - name: "Elaheh Jamali"
    username: ""
    year: 2021
  - name: "Hailey Barnett"
    username: ""
    year: 2021
  - name: "May Jue"
    username: ""
    year: 2021
  - name: "Hila Manalai"
    username: ""
    year: 2022
  - name: "Luis Jesus Riera Soto"
    username: "rieral"
    year: 2022
