lsfdb:
 db_name: "lsf"
 host: "db"
 username: "lsf_user"
 password: "password"

tracy:
 db_name: "UTE"
 host: "db"
 username: "tracy_user"
 password: "password"
 mssql_host: "timemachine1sql.berea.edu"
 mssql_user: "ute_limited"
 mssql_password: "REPLACE"

banner:
 user: "laborstatus"
 url: "bannerdbrh.berea.edu"
 port: 1521
 sid: "PPRD"
 password: "REPLACE"

secret_key: "123"
student_confirmation_days: 30
show_queries: True
use_banner: False

user:
 debug: "heggens"

financial_aid:
  email: "finaid@berea.edu"

ALWAYS_SEND_MAIL: True
MAIL_SERVER: "smtp.office365.com" #use smtp.gmail.com for gmail or smtp.office365.com for Berea
MAIL_PORT: 587 #: use port 465 for gmail use 587 for Berea
MAIL_USERNAME: 'ssdt@berea.edu' #the email of the sender
MAIL_PASSWORD: '' #Add the password of the sender
MAIL_USE_TLS: True # False for gmail, True for berea
MAIL_USE_SSL: False # True for gmail, False for berea
MAIL_DEFAULT_SENDER: 'ssdt@berea.edu' #Sender email address
MAIL_OVERRIDE_ALL: "laborstatusform-aaaaazdxy4j2lsinl67ikumy4y@studentprogrammers.slack.com"
REPLY_TO_ADDRESS: "laborstatusform-aaaaazdxy4j2lsinl67ikumy4y@studentprogrammers.slack.com"

VALID_REQUEST_IP: 'REPLACE'
