lsfdb:
 db_name: "lsf"
 host: "db"
 username: "lsf_user"
 password: "password"

tracy:
 db_name: "UTE"
 host: "db"
 username: "tracy_user"
 password: "password"


secret_key: "123"

user:
 debug: "heggens"


MAIL_SERVER: "smtp.gmail.com" #FIXME: use smtp.gmail.com for gmail mail.berea.edu for Berea
MAIL_PORT: 465 #: use port 465 for gmail use 25 for Berea
MAIL_USERNAME: 'ela.jamali09@gmail.com' #FIXME: add the email of the sender
MAIL_PASSWORD: 'fhirybivgcxhkwfr' #FIXME: Add the password of the sender
MAIL_USE_TLS: False
MAIL_USE_SSL: True
MAIL_DEFAULT_SENDER: 'ela.jamali09@gmail.com' #FIXME: Add sender email address
