lsfdb:
 db_name: "lsf"
 host: "db"
 username: "lsf_user"
 password: "password"

tracy:
 db_name: "UTE"
 host: "db"
 username: "tracy_user"
 password: "password"
 mssql_host: "timemachine1sql.berea.edu"
 mssql_user: "ute_limited"
 mssql_password: "REPLACE"

banner:
 user: "laborstatus"
 url: "bannerdbrh.berea.edu"
 port: 1521
 sid: "PPRD"
 password: "REPLACE"

secret_key: "123"

user:
 debug: "heggens"

financial_aid:
  email: "finaid@berea.edu"

ALWAYS_SEND_MAIL: False
MAIL_SERVER: "smtp.gmail.com" #FIXME: use smtp.gmail.com for gmail mail.berea.edu for Berea
MAIL_PORT: 465 #: use port 465 for gmail use 25 for Berea
MAIL_USERNAME: '' #FIXME: add the email of the sender
MAIL_PASSWORD: '' #FIXME: Add the password of the sender
REPLY_TO_ADDRESS: "labor_program@berea.edu"
MAIL_USE_TLS: False
MAIL_USE_SSL: True
MAIL_DEFAULT_SENDER: '' #FIXME: Add sender email address
MAIL_OVERRIDE_ALL: "j5u6j9w6v1h0p3g1@bereacs.slack.com"
