lsfdb:
  db_name: "lsf"
  host: "db"
  username: "lsf_user"
  password: "password"

tracy:
  db_name: "UTE"
  host: "db"
  username: "tracy_user"
  password: "password"

<<<<<<< HEAD:app/config/secret_config.yaml
contributors:
  - name: "Bria Williams"
    username: ""
    year: 2017
  - name: "Evan Johnson"
    username: "johnsone"
    year: 2019
  - name: "Katelyn Adams"
    username: ""
    year: 2019
  - name: "Alex Bryant"
    username: "bryantal"
    year: 2020
  - name: "Roberto Santos Hernandez"
    username: ""
    year: 2021
  - name: "Guillermo Cruz"
    username: ""
    year: 2021
  - name: "Elaheh Jamali"
    username: ""
    year: 2021
  - name: "Hailey Barnett"
    username: ""
    year: 2021
  - name: "May Jue"
    username: ""
    year: 2021
  - name: "Hila Manalai"
    username: ""
    year: 2022
  - name: "Luis Jesus Riera Soto"
    username: "rieral"
    year: 2022  
  - name: "Bria Williams"
    username: ""
    year: 2017
  - name: "Bria Williams"
    username: ""
    year: 2017
  - name: "Bria Williams"
    username: ""
    year: 2017  
=======
secret_key: "123"

user:
  debug: "heggens"
>>>>>>> cfeea4c60571e489f3d665a09d46b00f97b63e69:app/config/example.secret_config.yaml
