lsfdb:
  db_name: "lsf"
  host: "db"
  username: "lsf_user"
  password: "password"

tracy:
  db_name: "UTE"
  host: "db"
  username: "tracy_user"
  password: "password"

contributors:
  - name: "Bria Williams"
    username: ""
    year: 2017
  - name: "Evan Johnson"
    username: "johnsone"
    year: 2019
  - name: "Katelyn Adams"
    username: ""
    year: 2019
  - name: "Alex Bryant"
    username: "bryantal"
    year: 2020
  - name: "Roberto Santos Hernandez"
    username: ""
    year: 2021
  - name: "Guillermo Cruz"
    username: ""
    year: 2021
  - name: "Elaheh Jamali"
    username: ""
    year: 2021
  - name: "Hailey Barnett"
    username: ""
    year: 2021
  - name: "May Jue"
    username: ""
    year: 2021
  - name: "Hila Manalai"
    username: ""
    year: 2022
  - name: "Luis Jesus Riera Soto"
    username: "rieral"
    year: 2022  
  - name: "Bria Williams"
    username: ""
    year: 2017
  - name: "Bria Williams"
    username: ""
    year: 2017
  - name: "Bria Williams"
    username: ""
    year: 2017  