version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/home/vscode/lsf

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mysql
    restart: always
    environment: 
      MYSQL_DATABASE: 'lsf'
      MYSQL_USER: 'lsf_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3308:3308'
    expose:
      - '3308'
    volumes:
      - lsf_data:/var/lib/mysql
    
volumes:
  lsf_data: